using System;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
namespace DialogueImplementationTool.Extension;

public static class DialogTopicExtensions {
    public static RecordType ToRecordType(this DialogTopic.SubtypeEnum subtype) {
        return subtype switch {
            DialogTopic.SubtypeEnum.Custom => "CUST",
            DialogTopic.SubtypeEnum.ForceGreet => "PFGT",
            DialogTopic.SubtypeEnum.Rumors => "RUMO",
            DialogTopic.SubtypeEnum.Intimidate => "INTI",
            DialogTopic.SubtypeEnum.Flatter => "FLAT",
            DialogTopic.SubtypeEnum.Bribe => "BRIB",
            DialogTopic.SubtypeEnum.AskGift => "ASKG",
            DialogTopic.SubtypeEnum.Gift => "GIFF",
            DialogTopic.SubtypeEnum.AskFavor => "ASKF",
            DialogTopic.SubtypeEnum.Favor => "FAVO",
            DialogTopic.SubtypeEnum.ShowRelationships => "SHRE",
            DialogTopic.SubtypeEnum.Follow => "FOLL",
            DialogTopic.SubtypeEnum.Reject => "FRJT",
            DialogTopic.SubtypeEnum.Scene => "SCEN",
            DialogTopic.SubtypeEnum.Show => "SHOW",
            DialogTopic.SubtypeEnum.Agree => "AGRE",
            DialogTopic.SubtypeEnum.Refuse => "REFU",
            DialogTopic.SubtypeEnum.ExitFavorState => "FEXT",
            DialogTopic.SubtypeEnum.MoralRefusal => "MREF",
            DialogTopic.SubtypeEnum.FlyingMountLand => "FMLX",
            DialogTopic.SubtypeEnum.FlyingMountCancelLand => "FMXL",
            DialogTopic.SubtypeEnum.FlyingMountAcceptTarget => "FMAT",
            DialogTopic.SubtypeEnum.FlyingMountRejectTarget => "FMRT",
            DialogTopic.SubtypeEnum.FlyingMountNoTarget => "FMNT",
            DialogTopic.SubtypeEnum.FlyingMountDestinationReached => "FMDR",
            DialogTopic.SubtypeEnum.Attack => "ATCK",
            DialogTopic.SubtypeEnum.PowerAttack => "POAT",
            DialogTopic.SubtypeEnum.Bash => "BASH",
            DialogTopic.SubtypeEnum.Hit => "HIT_",
            DialogTopic.SubtypeEnum.Flee => "FLEE",
            DialogTopic.SubtypeEnum.Bleedout => "BLED",
            DialogTopic.SubtypeEnum.AvoidThreat => "AVTH",
            DialogTopic.SubtypeEnum.Death => "DETH",
            DialogTopic.SubtypeEnum.GroupStrategy => "GRST",
            DialogTopic.SubtypeEnum.Block => "BLOC",
            DialogTopic.SubtypeEnum.Taunt => "TAUT",
            DialogTopic.SubtypeEnum.AllyKilled => "ALKL",
            DialogTopic.SubtypeEnum.Steal => "STEA",
            DialogTopic.SubtypeEnum.Yield => "YIEL",
            DialogTopic.SubtypeEnum.AcceptYield => "ACYI",
            DialogTopic.SubtypeEnum.PickpocketCombat => "PICC",
            DialogTopic.SubtypeEnum.Assault => "ASSA",
            DialogTopic.SubtypeEnum.Murder => "MURD",
            DialogTopic.SubtypeEnum.AssaultNC => "ASNC",
            DialogTopic.SubtypeEnum.MurderNC => "MUNC",
            DialogTopic.SubtypeEnum.PickpocketNC => "PICN",
            DialogTopic.SubtypeEnum.StealFromNC => "STFN",
            DialogTopic.SubtypeEnum.TrespassAgainstNC => "TRAN",
            DialogTopic.SubtypeEnum.Trespass => "TRES",
            DialogTopic.SubtypeEnum.WerewolfTransformCrime => "WTCR",
            DialogTopic.SubtypeEnum.VoicePowerStartShort => "VPSS",
            DialogTopic.SubtypeEnum.VoicePowerStartLong => "VPSL",
            DialogTopic.SubtypeEnum.VoicePowerEndShort => "VPES",
            DialogTopic.SubtypeEnum.VoicePowerEndLong => "VPEL",
            DialogTopic.SubtypeEnum.AlertIdle => "ALIL",
            DialogTopic.SubtypeEnum.LostIdle => "LOIL",
            DialogTopic.SubtypeEnum.NormalToAlert => "NOTA",
            DialogTopic.SubtypeEnum.AlertToCombat => "ALTC",
            DialogTopic.SubtypeEnum.NormalToCombat => "NOTC",
            DialogTopic.SubtypeEnum.AlertToNormal => "ALTN",
            DialogTopic.SubtypeEnum.CombatToNormal => "COTN",
            DialogTopic.SubtypeEnum.CombatToLost => "COLO",
            DialogTopic.SubtypeEnum.LostToNormal => "LOTN",
            DialogTopic.SubtypeEnum.LostToCombat => "LOTC",
            DialogTopic.SubtypeEnum.DetectFriendDie => "DFDA",
            DialogTopic.SubtypeEnum.ServiceRefusal => "SERU",
            DialogTopic.SubtypeEnum.Repair => "REPA",
            DialogTopic.SubtypeEnum.Travel => "TRAV",
            DialogTopic.SubtypeEnum.Training => "TRAI",
            DialogTopic.SubtypeEnum.BarterExit => "BAEX",
            DialogTopic.SubtypeEnum.RepairExit => "REEX",
            DialogTopic.SubtypeEnum.Recharge => "RECH",
            DialogTopic.SubtypeEnum.RechargeExit => "RCEX",
            DialogTopic.SubtypeEnum.TrainingExit => "TREX",
            DialogTopic.SubtypeEnum.ObserveCombat => "OBCO",
            DialogTopic.SubtypeEnum.NoticeCorpse => "NOTI",
            DialogTopic.SubtypeEnum.TimeToGo => "TITG",
            DialogTopic.SubtypeEnum.Goodbye => "GBYE",
            DialogTopic.SubtypeEnum.Hello => "HELO",
            DialogTopic.SubtypeEnum.SwingMeleeWeapon => "SWMW",
            DialogTopic.SubtypeEnum.ShootBow => "FIWE",
            DialogTopic.SubtypeEnum.ZKeyObject => "ZKEY",
            DialogTopic.SubtypeEnum.Jump => "JUMP",
            DialogTopic.SubtypeEnum.KnockOverObject => "KNOO",
            DialogTopic.SubtypeEnum.DestroyObject => "DEOB",
            DialogTopic.SubtypeEnum.StandOnFurniture => "STOF",
            DialogTopic.SubtypeEnum.LockedObject => "LOOB",
            DialogTopic.SubtypeEnum.PickpocketTopic => "PICT",
            DialogTopic.SubtypeEnum.PursueIdleTopic => "PURS",
            DialogTopic.SubtypeEnum.SharedInfo => "IDAT",
            DialogTopic.SubtypeEnum.PlayerCastProjectileSpell => "PCPS",
            DialogTopic.SubtypeEnum.PlayerCastSelfSpell => "PCSS",
            DialogTopic.SubtypeEnum.PlayerShout => "PCSH",
            DialogTopic.SubtypeEnum.Idle => "IDLE",
            DialogTopic.SubtypeEnum.EnterSprintBreath => "BREA",
            DialogTopic.SubtypeEnum.EnterBowZoomBreath => "ENBZ",
            DialogTopic.SubtypeEnum.ExitBowZoomBreath => "EXBZ",
            DialogTopic.SubtypeEnum.ActorCollideWithActor => "ACAC",
            DialogTopic.SubtypeEnum.PlayerInIronSights => "PIRN",
            DialogTopic.SubtypeEnum.OutOfBreath => "OUTB",
            DialogTopic.SubtypeEnum.CombatGrunt => "GRNT",
            DialogTopic.SubtypeEnum.LeaveWaterBreath => "LWBS",
            _ => throw new ArgumentOutOfRangeException(nameof(subtype), subtype, null)
        };
    }
}
